package com.rags.tools.uter.vertical;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.eventbus.Message;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.SQLConnection;
import io.vertx.ext.sql.SQLOptions;

import java.util.List;

/**
 * Created by ragha on 22-04-2018.
 */
public class AbstractDBVerticle extends AbstractVerticle {

    private JDBCClient jdbcClient;

    public JDBCClient getJdbcClient() {
        if (jdbcClient == null) {
            String url = config().getString("db.url");
            String user = config().getString("db.user");
            String pass = config().getString("db.password");
            String driver = config().getString("db.driver");

            jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
                    .put("url", url)
                    .put("user", user)
                    .put("password", pass)
                    .put("driver_class", driver)
                    .put("max_pool_size", 5));
        }
        return jdbcClient;
    }

    void executeUpdate(String sql, JsonArray params, Message message) {
        executeUpdate(sql, params, message, Message::reply);
    }

    void executeUpdate(String sql, JsonArray params, Message message, ResultHandler<JsonObject> resultHandler) {
        getJdbcClient().getConnection(handler -> {
            if (handler.failed()) {
                message.fail(500, "Couldn't get DB Connections");
            } else {
                try (SQLConnection connection = handler.result()) {
                    connection.setOptions(new SQLOptions().setAutoGeneratedKeys(true));

                    connection.updateWithParams(sql, params, bill -> {
                        if (bill.failed()) {
                            message.fail(500, "Failed while creating item. Please retry");
                        } else {
                            message.reply(bill.result().getKeys().getInstant(0));
                        }
                    });
                } catch (Exception e) {
                    message.fail(500, e.getMessage());
                }
            }
        });
    }

    void executeBatchUpdate(String sql, List<JsonArray> params, Message message) {
        getJdbcClient().getConnection(handler -> {
            if (handler.failed()) {
                message.fail(500, "Failed while connecting to DB: " + handler.cause().getMessage());
            } else {
                try (SQLConnection connection = handler.result()) {
                    connection.batchWithParams(sql, params, res -> {
                        if (res.failed()) {
                            message.fail(500, "Failed while creati\ng BIll Item : " + res.cause().getMessage());
                        } else {
                            message.reply(res.result());
                        }
                    });
                } catch (Exception e) {
                    message.fail(500, e.getMessage());
                }
            }
        });
    }

    void executeGet(String sql, JsonArray params, Message message, ResultHandler<JsonArray> resultHandler) {
        getJdbcClient().getConnection(handler -> {
            if (handler.failed()) {
                message.fail(500, "Failed while connecting to DB: " + handler.cause().getMessage());
            } else {
                try (SQLConnection connection = handler.result()) {
                    connection.queryWithParams(sql, params, res -> {
                        if (res.failed()) {
                            message.fail(500, res.cause().getMessage());
                        } else {
                            resultHandler.handle(message, res.result().toJson().getJsonArray("rows"));
                        }
                    });
                } catch (Exception e) {
                    message.fail(500, e.getMessage());
                }
            }
        });
    }

    void executeGet(String sql, JsonArray params, Message message) {
        executeGet(sql, params, message, Message::reply);
    }

    interface ResultHandler<T> {
        void handle(Message message, T result);
    }
}
