export const USER_ACTION = {
	SAVE_UC:'SAVE_UC',
	RETRIEVE_UC:'RETRIEVE_UC',
	RETRIEVE_ALL:'RETRIEVE_ALL',
	RETRIEVE_ALL_EXECUTIONS:'RETRIEVE_ALL_EXECUTIONS',

	EXECUTE_UC : 'EXECUTE_UC',

	LOOKUP_USECASES: 'LOOKUP_USECASES'
}

export const REDUX_ACTION = {
	RETRIEVE_ALL:'RETRIEVE_ALL',
	UC_RESULT:'UC_RESULT',
	ALL_EXECUTIONS:'ALL_EXECUTIONS',
    LAUNCH_MODAL: 'LAUNCH_MODAL'
}
